core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('navigation.urls')),
]

core/navigation/urls.py
from django.urls import path
from . import views

app_name = 'navigation'   # 👈 এই লাইনটা যোগ করো

urlpatterns = [
    path('', views.home, name='home'),
    path('news/', views.news, name='news'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

core/navigation/models.py
from django.db import models

# Create your models here.

core/navigation/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def home(request):
    return render(request, 'navigation/index.html')

def news(request):
    return render(request, 'navigation/news.html')

def about(request):
    return render(request, 'navigation/about.html')

def contact(request):
    return render(request, 'navigation/contact.html')

core/templates/navigation/about.html
{% extends 'navigation/base.html' %}

<title>
  {% block title %}
   About Page
  {% endblock %}
</title>



{% block content %}
  <h2>About Page</h2>
{% endblock %}

core/templates/navigation/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

<title>

  {% block title %}
  
  {% endblock %}

</title>


<link rel="stylesheet" href="{% static 'navigation/style.css' %}">
</head>
<body>

    <!-- Navbar -->
    {% include 'navigation/includes/header.html' %}

    <!-- Main Content -->
     {% block content %}

     {% endblock %}


<!-- <ul>
  <li><a href="{% url 'navigation:home' %}">Home</a></li>
  <li><a href="{% url 'navigation:news' %}">News</a></li>
  <li><a href="{% url 'navigation:about' %}">About</a></li>
  <li><a href="{% url 'navigation:contact' %}">Contact</a></li>

</ul> -->
</body>
</html>

core/templates/navigation/contact.html
{% extends 'navigation/base.html' %}

<title>
  {% block title %}
   Contact Page
  {% endblock %}
</title>



{% block content %}
  <h2>Contact Page</h2>
{% endblock %}

core/templates/navigation/includes/header.html
<ul>
  <li><a href="{% url 'navigation:home' %}">Home</a></li>
  <li><a href="{% url 'navigation:news' %}">News</a></li>
  <li><a href="{% url 'navigation:about' %}">About</a></li>
  <li><a href="{% url 'navigation:contact' %}">Contact</a></li>

</ul>

core/templates/navigation/index.html
{% extends "navigation/base.html" %}

<title>

  {% block title %}
    Home Page
  {% endblock %}

</title>



{% block content %}
<h2>Home Page</h2>
{% endblock %}

core/templates/navigation/news.html
{% extends 'navigation/base.html' %}

<title>
  {% block title %}
   News Page
  {% endblock %}
</title>


{% block content %}
  <h2>News Page</h2>
{% endblock %}